souretreeでのcommit時にもswiftformatが走るように修正

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# PATH を設定（swiftformat のパスを追加）
+export PATH="/opt/homebrew/bin:$PATH"
+
 # swiftformat を --lint オプション付きで実行
 swiftformat --lint .
 
@@ -11,13 +14,13 @@ if [ $exit_code -ne 0 ]; then
   # フォーマットの必要があるので実行
   swiftformat .
 
-    echo "Error: This commit was cancelled due to formatting changes."
-    echo "Error: Please fix the errors and then commit again."
-    echo "Hint: You can check the changes with git diff."
-    echo "Info: This check can also be skipped with '% git commit --no-verify'. Not recommended."
+  echo "Error: This commit was cancelled due to formatting changes."
+  echo "Error: Please fix the errors and then commit again."
+  echo "Hint: You can check the changes with git diff."
+  echo "Info: This check can also be skipped with '% git commit --no-verify'. Not recommended."
 
-    # コミットを中断
-    exit 1
+  # コミットを中断
+  exit 1
 fi
 
 echo "No formatting issues detected. Proceeding with commit."
